### ISSUE TITLE
Can this method scale-up to larger models?

### ISSUE THREAD

**Issue by chenwydj** [fmi-basel/neural-tangent-transfer#2]
Dear authors,

This is a great work and I love it!

I wonder if this method can be scaled up for larger models, like ResNet18/32/50?

Thank you!

**Comment by liutianlin0121** [comment]
Hi Wuyang,

Thanks for your interest! Around ~1 year ago when the project was conducted, computing the empirical NTK tends to be slow. For this reason, scaling to ResNet was difficult at that time. But it seems that the computational efficiency of [neural-tangent](https://github.com/google/neural-tangents) package has been greatly boosted since then, so perhaps scaling to ResNet is possible now -- I didn't follow the development of the neural-tangent package lately, but I imagine that the scalability of our approach critically depends on the scalability of this package. 

Cheers,
Tianlin

**Comment by chenwydj** [comment]
Thank you very much for your explanation!
