### ISSUE TITLE
Pruned weights in NTK

### ISSUE THREAD

**Issue by chenwydj** [fmi-basel/neural-tangent-transfer#3]
For pruned neurons (weights), they do not involve both forward and backward.

Was this considered in [empirical_ntk_fn](https://github.com/fmi-basel/neural-tangent-transfer/blob/master/nt_transfer/utils.py#L73)? For example, perhaps the pruned weights should have their gradients set as 0 during NTK calculation?

Thank you very much for your help!

**Comment by liutianlin0121** [comment]
Hi Wuyang, 

Thanks for the question. Hmmm, I guess I forgot some details -- are you observing non-zero gradient for pruned weights during NTT?

Perhaps one reason for not setting the gradients of pruned weights to be zero is that we still want these weights to evolve during NTT training. Recall that NTT is a two-step scheme: In the first step we fix a mask and train the weights; in the second step we re-select the mask based on the current magnitude of all weights. Heuristically, allowing all weights to receive gradient could help the second, mask selection step --  otherwise, those unpruned weights associated with the initial mask may have magnitudes much greater than those pruned weights during training, and the mask may never change because pruned weights do not get updated. 

That being said, setting gradients of pruned weights to 0 may also work -- I forgot whether I compared their convergence speed or not.

Cheers,
Tianlin

**Comment by chenwydj** [comment]
Thank you very much for your explanation! @liutianlin0121 

I was just concerned if the NTK of the sparse network is correctly calculated when the pruned neurons still involve backward. But I understand your rationale.

**Comment by liutianlin0121** [comment]
no problem.
